title: abbayatahini
description: Ethiopian tahini in Portugal
baseurl: ""
url: "https://abbayatahini.github.io/abbaya"

# Build settings
markdown: kramdown

# Language settings
default_lang: pt

languages:
  - pt
  - en
